### ISSUE TITLE
System.IO.FileNotFoundException : Could not load file or assembly Weighted Randomized Net Standard

### ISSUE THREAD

**Issue by somnus0x** [BlueRaja/Weighted-Item-Randomizer-for-C-Sharp#4]
Did you added nuget for .netstandard?

```System.IO.FileNotFoundException : Could not load file or assembly 'Weighted Randomized Net Standard, Version=1.0.2.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.```
while there is only `Weighted Randomized.dll` in ~./nuget/packages.

**Comment by somnus0x** [comment]
And `Weighted_Randomized_Net_Standard` namespace have nothing

**Comment by BlueRaja** [comment]
The namespace should be the same, `Weighted_Randomizer`

https://github.com/BlueRaja/Weighted-Item-Randomizer-for-C-Sharp/blob/master/Weighted%20Randomizer/Weighted%20Randomizer.nuspec#L22-L24

I haven't tested that aspect so it's possible I did something wrong.

[Edit] I did just notice I named the folder `Weighted Randomized Net Standard` instead of `Weighted Randomizer Net Standard`, whoops.  But nowhere is there a `Weighted Randomized.dll`.  It should be `Weighted Randomizer.dll`

**Comment by markwagoner** [comment]
So how do you get around this issue?  I am trying to convert a project from .net framework to .net core 2.2 and I am getting the same error.

**Comment by brickman1444** [comment]
I also hit this issue on a .net core project and it made this package unusable for me.

**Comment by BlueRaja** [comment]
Fixed in v1.0.3

**Comment by johnrom** [comment]
I'm still seeing this issue in 1.0.3.

```
Exception has occurred: CLR/System.IO.FileNotFoundException
An unhandled exception of type 'System.IO.FileNotFoundException' occurred in System.Private.CoreLib.dll: 'Could not load file or assembly 'Weighted Randomizer Net Standard, Version=1.0.3.0, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.'
```

(Note it says Randomizer and not Randomized like 1.0.2, so the fix appears to be there but maybe doesn't cover all cases?).
